services:
  postgres:
    image: postgres
    container_name: goodbuy_postgres
    environment:
      POSTGRES_PASSWORD: ${DEFAULT_DB_PASSWORD}
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data